name: After push develop
on:
  push:
    branches:
      - develop

jobs:
  Homolog:
    name: Promote Homolog
    needs: [CD]
    environment:
      name: deploymentconfig.homolog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist

      - name: Apply target
        uses: w9jds/firebase-action@master
        with:
          args: target:apply hosting web-vue-test-ci-homolog homolog
        env:
          FIREBASE_TOKEN: ${{ secrets.FirebaseDeploy }}

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:web-vue-test-ci-homolog
        env:
          FIREBASE_TOKEN: ${{ secrets.FirebaseDeploy }}
  
  Production:
    name: Promote Production
    needs: [Homolog]
    environment:
      name: deploymentconfig.prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist

      - name: Apply target
        uses: w9jds/firebase-action@master
        with:
          args: target:apply hosting web-vue-test-ci prod
        env:
          FIREBASE_TOKEN: ${{ secrets.FirebaseDeploy }}

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:web-vue-test-ci
        env:
          FIREBASE_TOKEN: ${{ secrets.FirebaseDeploy }}
