name: Vue App CI/CD
on: [push, pull_request, workflow_dispatch]

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
      - name: Run Jest - Unit Tests
        run: npm run test:unit
      - name: Run Cypress - Integration Tests
        run: npm run test:e2e:ci
      
  sonarqube:
    name: Code Quality
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  
  horusec:
    name: SAST
    needs: build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: SAST - Running Horusec Security
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
          horusec start -p="./" -e="true"  

  CD:
    needs: [build, sonarqube, horusec]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist

      - name: Apply target
        uses: w9jds/firebase-action@master
        with:
          args: target:apply hosting web-vue-test-ci-dev dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FirebaseDeploy }}

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:web-vue-test-ci-dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FirebaseDeploy }}
  
  Homolog:
    name: Promote Homolog
    needs: [CD]
    environment:
      name: deploymentconfig.homolog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist

      - name: Apply target
        uses: w9jds/firebase-action@master
        with:
          args: target:apply hosting web-vue-test-ci-homolog homolog
        env:
          FIREBASE_TOKEN: ${{ secrets.FirebaseDeploy }}

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:web-vue-test-ci-homolog
        env:
          FIREBASE_TOKEN: ${{ secrets.FirebaseDeploy }}
  
  Production:
    name: Promote Production
    needs: [Homolog]
    environment:
      name: deploymentconfig.prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist

      - name: Apply target
        uses: w9jds/firebase-action@master
        with:
          args: target:apply hosting web-vue-test-ci prod
        env:
          FIREBASE_TOKEN: ${{ secrets.FirebaseDeploy }}

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:web-vue-test-ci
        env:
          FIREBASE_TOKEN: ${{ secrets.FirebaseDeploy }}
