on: [push, pull_request, workflow_dispatch]

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:      
      # - name: DockerHub Login
      #   uses: docker/login-action@v1.10.0      
      #   with:
      #     username: ${{ secrets.DOCKERHUB_LOGIN }}
      #     password: ${{ secrets.DOCKERHUB_PASS }}   
      # - name: Build Artefacts
      #   uses: docker/build-push-action@v2.6.1
      #   with: 
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: |
      #       andersoncmciet/web-vue-test-ci:latest
      #       andersoncmciet/web-vue-test-ci:${{ github.run_number }}
      
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: SAST - Running Horusec Security
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
          horusec start -p="./" -e="true"   
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist

      - name: Run Jest - Unit Tests
        run: npm run test:unit

      - name: Run Cypress - Integration Tests
        run: npm run test:e2e:ci

  deploy:
    name: Deploy
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FirebaseDeploy }}
