name: Vue App CI/CD
on: [push, pull_request, workflow_dispatch]

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
      
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist

      - name: Run Jest - Unit Tests
        run: npm run test:unit
      - name: Run Cypress - Integration Tests
        run: npm run test:e2e:ci
      
  sonarqube:
    name: Code Quality
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  CD:
    needs: [build, sonarqube, Veracode_PipelineScan]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist

      - name: Apply target
        uses: w9jds/firebase-action@master
        with:
          args: target:apply hosting web-vue-test-ci-dev dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FirebaseDeploy }}

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:web-vue-test-ci-dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FirebaseDeploy }}
  
  Homolog:
    name: Promote Homolog
    needs: [CD]
    environment:
      name: deploymentconfig.homolog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist

      - name: Apply target
        uses: w9jds/firebase-action@master
        with:
          args: target:apply hosting web-vue-test-ci-homolog homolog
        env:
          FIREBASE_TOKEN: ${{ secrets.FirebaseDeploy }}

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:web-vue-test-ci-homolog
        env:
          FIREBASE_TOKEN: ${{ secrets.FirebaseDeploy }}

  # Cenário de subir a versão
  Veracode_SAST_REPORTS:
    name: SAST Reports
    runs-on: ubuntu-latest
    needs: [Homolog]
    environment:
      name: secutiy-tools-to-prepare.prod
    steps:
      - name: Download Artefato
        uses: actions/download-artifact@v2
        with:
          name: pacoteVeracode
      - uses: veracode/veracode-uploadandscan-action@master # Faz a analise da Veracode
        env:
          VID: ${{ secrets.VID }} # Lembrar de criar as credenciais no Secrets
          VKEY: ${{ secrets.VKEY }}
          AppName: Github Actions - ${{ github.repository }}
        with:
          vid: '$VID'
          vkey: '$VKEY'
          criticality: 'VeryHigh'
          appname: '$AppName'
          createsandbox: true
          sandboxname: pre-prod
          filepath: 'veracode.zip'
          deleteIncompleteScan: false
          version: ${{ github.run_id }}

  Production:
    name: Promote Production
    needs: [Homolog]
    environment:
      name: deploymentconfig.prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist

      - name: Apply target
        uses: w9jds/firebase-action@master
        with:
          args: target:apply hosting web-vue-test-ci prod
        env:
          FIREBASE_TOKEN: ${{ secrets.FirebaseDeploy }}

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:web-vue-test-ci
        env:
          FIREBASE_TOKEN: ${{ secrets.FirebaseDeploy }}
