on: [push, pull_request, workflow_dispatch]

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Download Code
        uses: actions/checkout@v2
      - name: SAST - Running Horusec Security
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
          horusec start -p="./" -e="true"   
      - name: DockerHub Login
        uses: docker/login-action@v1.10.0      
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASS }}   
      - name: Build Artefacts
        uses: docker/build-push-action@v2.6.1
        with: 
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            andersoncmciet/web-vue-test-ci:latest
            andersoncmciet/web-vue-test-ci:${{ github.run_number }}
      
      - name: Install Dependencies
        run: npm ci

      - name: Run Jest - Unit Tests
        run: npm run test:unit

      - name: Build app
        run: npm run build

      - name: Run Cypress - Integration Tests
        run: npm run test:e2e:ci


  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - name: Download Code
      uses: actions/checkout@v2

    - name: Deploy with Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        # see via cmd: firebase login:ci
        FIREBASE_TOKEN: ${{ secrets.FirebaseDeploy }}